// Code generated by goctl. DO NOT EDIT.
// Source: koala.proto

package server

import (
	"context"

	"koala/gateway/internal/logic/menu"
	"koala/gateway/internal/svc"
	"koala/gateway/pb"
)

type MenuServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMenuServer
}

func NewMenuServer(svcCtx *svc.ServiceContext) *MenuServer {
	return &MenuServer{
		svcCtx: svcCtx,
	}
}

func (s *MenuServer) CreateMenu(ctx context.Context, in *pb.MenuReq) (*pb.EmptyResp, error) {
	l := menulogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *MenuServer) UpdateMenu(ctx context.Context, in *pb.MenuReq) (*pb.EmptyResp, error) {
	l := menulogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *MenuServer) DeleteMenus(ctx context.Context, in *pb.DeletesReq) (*pb.EmptyResp, error) {
	l := menulogic.NewDeleteMenusLogic(ctx, s.svcCtx)
	return l.DeleteMenus(in)
}

func (s *MenuServer) GetMenuTree(ctx context.Context, in *pb.MenuQueryReq) (*pb.MenusResp, error) {
	l := menulogic.NewGetMenuTreeLogic(ctx, s.svcCtx)
	return l.GetMenuTree(in)
}

func (s *MenuServer) GetUserMenuList(ctx context.Context, in *pb.UserReq) (*pb.UserMenusResp, error) {
	l := menulogic.NewGetUserMenuListLogic(ctx, s.svcCtx)
	return l.GetUserMenuList(in)
}

func (s *MenuServer) GetMenuForRole(ctx context.Context, in *pb.PermsReq) (*pb.PermsResp, error) {
	l := menulogic.NewGetMenuForRoleLogic(ctx, s.svcCtx)
	return l.GetMenuForRole(in)
}
