// Code generated by goctl. DO NOT EDIT.
// Source: koala.proto

package server

import (
	"context"

	"koala/gateway/internal/logic/application"
	"koala/gateway/internal/svc"
	"koala/gateway/pb"
)

type ApplicationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedApplicationServer
}

func NewApplicationServer(svcCtx *svc.ServiceContext) *ApplicationServer {
	return &ApplicationServer{
		svcCtx: svcCtx,
	}
}

func (s *ApplicationServer) CreateSysApplication(ctx context.Context, in *pb.CreateSysApplicationReq) (*pb.CreateSysApplicationResp, error) {
	l := applicationlogic.NewCreateSysApplicationLogic(ctx, s.svcCtx)
	return l.CreateSysApplication(in)
}

func (s *ApplicationServer) UpdateSysApplication(ctx context.Context, in *pb.UpdateSysApplicationReq) (*pb.UpdateSysApplicationResp, error) {
	l := applicationlogic.NewUpdateSysApplicationLogic(ctx, s.svcCtx)
	return l.UpdateSysApplication(in)
}

func (s *ApplicationServer) DeleteSysApplication(ctx context.Context, in *pb.DeleteSysApplicationReq) (*pb.DeleteSysApplicationResp, error) {
	l := applicationlogic.NewDeleteSysApplicationLogic(ctx, s.svcCtx)
	return l.DeleteSysApplication(in)
}

func (s *ApplicationServer) DetailSysApplication(ctx context.Context, in *pb.DetailSysApplicationReq) (*pb.DetailSysApplicationResp, error) {
	l := applicationlogic.NewDetailSysApplicationLogic(ctx, s.svcCtx)
	return l.DetailSysApplication(in)
}

func (s *ApplicationServer) PageSysApplication(ctx context.Context, in *pb.SearchSysApplicationReq) (*pb.SearchSysApplicationResp, error) {
	l := applicationlogic.NewPageSysApplicationLogic(ctx, s.svcCtx)
	return l.PageSysApplication(in)
}
