// Code generated by goctl. DO NOT EDIT.
// Source: koala.proto

package client

import (
	"context"

	"koala/gateway/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountListResp          = pb.AccountListResp
	AccountQueryReq          = pb.AccountQueryReq
	AccountReq               = pb.AccountReq
	ApiListResp              = pb.ApiListResp
	ApiQueryReq              = pb.ApiQueryReq
	ApiReq                   = pb.ApiReq
	BoolRep                  = pb.BoolRep
	CreateSysApplicationReq  = pb.CreateSysApplicationReq
	CreateSysApplicationResp = pb.CreateSysApplicationResp
	DeleteSysApplicationReq  = pb.DeleteSysApplicationReq
	DeleteSysApplicationResp = pb.DeleteSysApplicationResp
	DeletesReq               = pb.DeletesReq
	DeptListResp             = pb.DeptListResp
	DeptQueryReq             = pb.DeptQueryReq
	DeptReq                  = pb.DeptReq
	DetailSysApplicationReq  = pb.DetailSysApplicationReq
	DetailSysApplicationResp = pb.DetailSysApplicationResp
	EmptyReq                 = pb.EmptyReq
	EmptyResp                = pb.EmptyResp
	GenerateTokenReq         = pb.GenerateTokenReq
	GenerateTokenResp        = pb.GenerateTokenResp
	GetUserInfoReq           = pb.GetUserInfoReq
	GetUserInfoResp          = pb.GetUserInfoResp
	IdReq                    = pb.IdReq
	IdsResp                  = pb.IdsResp
	LoginReq                 = pb.LoginReq
	LoginResp                = pb.LoginResp
	MenuQueryReq             = pb.MenuQueryReq
	MenuReq                  = pb.MenuReq
	MenusListResp            = pb.MenusListResp
	MenusListResp_MenuMeta   = pb.MenusListResp_MenuMeta
	MenusResp                = pb.MenusResp
	Permission               = pb.Permission
	PermsReq                 = pb.PermsReq
	PermsResp                = pb.PermsResp
	PolicyReq                = pb.PolicyReq
	PostListResp             = pb.PostListResp
	PostQueryReq             = pb.PostQueryReq
	PostReq                  = pb.PostReq
	QueryReq                 = pb.QueryReq
	RegisterReq              = pb.RegisterReq
	RegisterResp             = pb.RegisterResp
	ResetPasswordReq         = pb.ResetPasswordReq
	RoleBindReq              = pb.RoleBindReq
	RoleListResp             = pb.RoleListResp
	RolePermission           = pb.RolePermission
	RoleQueryReq             = pb.RoleQueryReq
	RoleReq                  = pb.RoleReq
	RuleResp                 = pb.RuleResp
	RulesReq                 = pb.RulesReq
	SearchSysApplicationReq  = pb.SearchSysApplicationReq
	SearchSysApplicationResp = pb.SearchSysApplicationResp
	SysApplicationView       = pb.SysApplicationView
	UpdatePasswordReq        = pb.UpdatePasswordReq
	UpdateSysApplicationReq  = pb.UpdateSysApplicationReq
	UpdateSysApplicationResp = pb.UpdateSysApplicationResp
	User                     = pb.User
	UserMenusResp            = pb.UserMenusResp
	UserPermsVerifyReq       = pb.UserPermsVerifyReq
	UserReq                  = pb.UserReq

	Menu interface {
		CreateMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*EmptyResp, error)
		UpdateMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*EmptyResp, error)
		DeleteMenus(ctx context.Context, in *DeletesReq, opts ...grpc.CallOption) (*EmptyResp, error)
		GetMenuTree(ctx context.Context, in *MenuQueryReq, opts ...grpc.CallOption) (*MenusResp, error)
		GetUserMenuList(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserMenusResp, error)
		GetMenuForRole(ctx context.Context, in *PermsReq, opts ...grpc.CallOption) (*PermsResp, error)
	}

	defaultMenu struct {
		cli zrpc.Client
	}
)

func NewMenu(cli zrpc.Client) Menu {
	return &defaultMenu{
		cli: cli,
	}
}

func (m *defaultMenu) CreateMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultMenu) UpdateMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultMenu) DeleteMenus(ctx context.Context, in *DeletesReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.DeleteMenus(ctx, in, opts...)
}

func (m *defaultMenu) GetMenuTree(ctx context.Context, in *MenuQueryReq, opts ...grpc.CallOption) (*MenusResp, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.GetMenuTree(ctx, in, opts...)
}

func (m *defaultMenu) GetUserMenuList(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserMenusResp, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.GetUserMenuList(ctx, in, opts...)
}

func (m *defaultMenu) GetMenuForRole(ctx context.Context, in *PermsReq, opts ...grpc.CallOption) (*PermsResp, error) {
	client := pb.NewMenuClient(m.cli.Conn())
	return client.GetMenuForRole(ctx, in, opts...)
}
