// Code generated by goctl. DO NOT EDIT.
// Source: koala.proto

package client

import (
	"context"

	"koala/gateway/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountListResp          = pb.AccountListResp
	AccountQueryReq          = pb.AccountQueryReq
	AccountReq               = pb.AccountReq
	ApiListResp              = pb.ApiListResp
	ApiQueryReq              = pb.ApiQueryReq
	ApiReq                   = pb.ApiReq
	BoolRep                  = pb.BoolRep
	CreateSysApplicationReq  = pb.CreateSysApplicationReq
	CreateSysApplicationResp = pb.CreateSysApplicationResp
	DeleteSysApplicationReq  = pb.DeleteSysApplicationReq
	DeleteSysApplicationResp = pb.DeleteSysApplicationResp
	DeletesReq               = pb.DeletesReq
	DeptListResp             = pb.DeptListResp
	DeptQueryReq             = pb.DeptQueryReq
	DeptReq                  = pb.DeptReq
	DetailSysApplicationReq  = pb.DetailSysApplicationReq
	DetailSysApplicationResp = pb.DetailSysApplicationResp
	EmptyReq                 = pb.EmptyReq
	EmptyResp                = pb.EmptyResp
	GenerateTokenReq         = pb.GenerateTokenReq
	GenerateTokenResp        = pb.GenerateTokenResp
	GetUserInfoReq           = pb.GetUserInfoReq
	GetUserInfoResp          = pb.GetUserInfoResp
	IdReq                    = pb.IdReq
	IdsResp                  = pb.IdsResp
	LoginReq                 = pb.LoginReq
	LoginResp                = pb.LoginResp
	MenuQueryReq             = pb.MenuQueryReq
	MenuReq                  = pb.MenuReq
	MenusListResp            = pb.MenusListResp
	MenusListResp_MenuMeta   = pb.MenusListResp_MenuMeta
	MenusResp                = pb.MenusResp
	Permission               = pb.Permission
	PermsReq                 = pb.PermsReq
	PermsResp                = pb.PermsResp
	PolicyReq                = pb.PolicyReq
	PostListResp             = pb.PostListResp
	PostQueryReq             = pb.PostQueryReq
	PostReq                  = pb.PostReq
	QueryReq                 = pb.QueryReq
	RegisterReq              = pb.RegisterReq
	RegisterResp             = pb.RegisterResp
	ResetPasswordReq         = pb.ResetPasswordReq
	RoleBindReq              = pb.RoleBindReq
	RoleListResp             = pb.RoleListResp
	RolePermission           = pb.RolePermission
	RoleQueryReq             = pb.RoleQueryReq
	RoleReq                  = pb.RoleReq
	RuleResp                 = pb.RuleResp
	RulesReq                 = pb.RulesReq
	SearchSysApplicationReq  = pb.SearchSysApplicationReq
	SearchSysApplicationResp = pb.SearchSysApplicationResp
	SysApplicationView       = pb.SysApplicationView
	UpdatePasswordReq        = pb.UpdatePasswordReq
	UpdateSysApplicationReq  = pb.UpdateSysApplicationReq
	UpdateSysApplicationResp = pb.UpdateSysApplicationResp
	User                     = pb.User
	UserMenusResp            = pb.UserMenusResp
	UserPermsVerifyReq       = pb.UserPermsVerifyReq
	UserReq                  = pb.UserReq

	Account interface {
		CreateAccount(ctx context.Context, in *AccountReq, opts ...grpc.CallOption) (*EmptyResp, error)
		UpdateAccount(ctx context.Context, in *AccountReq, opts ...grpc.CallOption) (*EmptyResp, error)
		DeleteAccounts(ctx context.Context, in *DeletesReq, opts ...grpc.CallOption) (*EmptyResp, error)
		PageAccount(ctx context.Context, in *AccountQueryReq, opts ...grpc.CallOption) (*AccountListResp, error)
		UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*EmptyResp, error)
		ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*EmptyResp, error)
		RegisterUser(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		LoginUser(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) CreateAccount(ctx context.Context, in *AccountReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.CreateAccount(ctx, in, opts...)
}

func (m *defaultAccount) UpdateAccount(ctx context.Context, in *AccountReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.UpdateAccount(ctx, in, opts...)
}

func (m *defaultAccount) DeleteAccounts(ctx context.Context, in *DeletesReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.DeleteAccounts(ctx, in, opts...)
}

func (m *defaultAccount) PageAccount(ctx context.Context, in *AccountQueryReq, opts ...grpc.CallOption) (*AccountListResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.PageAccount(ctx, in, opts...)
}

func (m *defaultAccount) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in, opts...)
}

func (m *defaultAccount) ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.ResetPassword(ctx, in, opts...)
}

func (m *defaultAccount) RegisterUser(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.RegisterUser(ctx, in, opts...)
}

func (m *defaultAccount) LoginUser(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.LoginUser(ctx, in, opts...)
}

func (m *defaultAccount) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultAccount) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	client := pb.NewAccountClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}
