// Code generated by goctl. DO NOT EDIT.
// Source: koala.proto

package server

import (
	"context"

	"koala/gateway/internal/logic/post"
	"koala/gateway/internal/svc"
	"koala/gateway/pb"
)

type PostServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPostServer
}

func NewPostServer(svcCtx *svc.ServiceContext) *PostServer {
	return &PostServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServer) CreatePost(ctx context.Context, in *pb.PostReq) (*pb.EmptyResp, error) {
	l := postlogic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *PostServer) UpdatePost(ctx context.Context, in *pb.PostReq) (*pb.EmptyResp, error) {
	l := postlogic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *PostServer) DeletePost(ctx context.Context, in *pb.DeletesReq) (*pb.EmptyResp, error) {
	l := postlogic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *PostServer) PagePost(ctx context.Context, in *pb.PostQueryReq) (*pb.PostListResp, error) {
	l := postlogic.NewPagePostLogic(ctx, s.svcCtx)
	return l.PagePost(in)
}
