// Code generated by goctl. DO NOT EDIT.
// Source: koala.proto

package server

import (
	"context"

	"koala/gateway/internal/logic/role"
	"koala/gateway/internal/svc"
	"koala/gateway/pb"
)

type RoleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRoleServer
}

func NewRoleServer(svcCtx *svc.ServiceContext) *RoleServer {
	return &RoleServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleServer) CreateRole(ctx context.Context, in *pb.RoleReq) (*pb.EmptyResp, error) {
	l := rolelogic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *RoleServer) UpdateRole(ctx context.Context, in *pb.RoleReq) (*pb.EmptyResp, error) {
	l := rolelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *RoleServer) DeleteRole(ctx context.Context, in *pb.DeletesReq) (*pb.EmptyResp, error) {
	l := rolelogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

func (s *RoleServer) PageRole(ctx context.Context, in *pb.RoleQueryReq) (*pb.RoleListResp, error) {
	l := rolelogic.NewPageRoleLogic(ctx, s.svcCtx)
	return l.PageRole(in)
}
