// Code generated by goctl. DO NOT EDIT.
// Source: koala.proto

package server

import (
	"context"

	"koala/gateway/internal/logic/dept"
	"koala/gateway/internal/svc"
	"koala/gateway/pb"
)

type DeptServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDeptServer
}

func NewDeptServer(svcCtx *svc.ServiceContext) *DeptServer {
	return &DeptServer{
		svcCtx: svcCtx,
	}
}

func (s *DeptServer) CreateDept(ctx context.Context, in *pb.DeptReq) (*pb.EmptyResp, error) {
	l := deptlogic.NewCreateDeptLogic(ctx, s.svcCtx)
	return l.CreateDept(in)
}

func (s *DeptServer) UpdateDept(ctx context.Context, in *pb.DeptReq) (*pb.EmptyResp, error) {
	l := deptlogic.NewUpdateDeptLogic(ctx, s.svcCtx)
	return l.UpdateDept(in)
}

func (s *DeptServer) DeleteDept(ctx context.Context, in *pb.DeletesReq) (*pb.EmptyResp, error) {
	l := deptlogic.NewDeleteDeptLogic(ctx, s.svcCtx)
	return l.DeleteDept(in)
}

func (s *DeptServer) PageDept(ctx context.Context, in *pb.DeptQueryReq) (*pb.DeptListResp, error) {
	l := deptlogic.NewPageDeptLogic(ctx, s.svcCtx)
	return l.PageDept(in)
}
