// Code generated by goctl. DO NOT EDIT.
// Source: koala.proto

package client

import (
	"context"

	"koala/gateway/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountListResp          = pb.AccountListResp
	AccountQueryReq          = pb.AccountQueryReq
	AccountReq               = pb.AccountReq
	ApiListResp              = pb.ApiListResp
	ApiQueryReq              = pb.ApiQueryReq
	ApiReq                   = pb.ApiReq
	BoolRep                  = pb.BoolRep
	CreateSysApplicationReq  = pb.CreateSysApplicationReq
	CreateSysApplicationResp = pb.CreateSysApplicationResp
	DeleteSysApplicationReq  = pb.DeleteSysApplicationReq
	DeleteSysApplicationResp = pb.DeleteSysApplicationResp
	DeletesReq               = pb.DeletesReq
	DeptListResp             = pb.DeptListResp
	DeptQueryReq             = pb.DeptQueryReq
	DeptReq                  = pb.DeptReq
	DetailSysApplicationReq  = pb.DetailSysApplicationReq
	DetailSysApplicationResp = pb.DetailSysApplicationResp
	EmptyReq                 = pb.EmptyReq
	EmptyResp                = pb.EmptyResp
	GenerateTokenReq         = pb.GenerateTokenReq
	GenerateTokenResp        = pb.GenerateTokenResp
	GetUserInfoReq           = pb.GetUserInfoReq
	GetUserInfoResp          = pb.GetUserInfoResp
	IdReq                    = pb.IdReq
	IdsResp                  = pb.IdsResp
	LoginReq                 = pb.LoginReq
	LoginResp                = pb.LoginResp
	MenuQueryReq             = pb.MenuQueryReq
	MenuReq                  = pb.MenuReq
	MenusListResp            = pb.MenusListResp
	MenusListResp_MenuMeta   = pb.MenusListResp_MenuMeta
	MenusResp                = pb.MenusResp
	Permission               = pb.Permission
	PermsReq                 = pb.PermsReq
	PermsResp                = pb.PermsResp
	PolicyReq                = pb.PolicyReq
	PostListResp             = pb.PostListResp
	PostQueryReq             = pb.PostQueryReq
	PostReq                  = pb.PostReq
	QueryReq                 = pb.QueryReq
	RegisterReq              = pb.RegisterReq
	RegisterResp             = pb.RegisterResp
	ResetPasswordReq         = pb.ResetPasswordReq
	RoleBindReq              = pb.RoleBindReq
	RoleListResp             = pb.RoleListResp
	RolePermission           = pb.RolePermission
	RoleQueryReq             = pb.RoleQueryReq
	RoleReq                  = pb.RoleReq
	RuleResp                 = pb.RuleResp
	RulesReq                 = pb.RulesReq
	SearchSysApplicationReq  = pb.SearchSysApplicationReq
	SearchSysApplicationResp = pb.SearchSysApplicationResp
	SysApplicationView       = pb.SysApplicationView
	UpdatePasswordReq        = pb.UpdatePasswordReq
	UpdateSysApplicationReq  = pb.UpdateSysApplicationReq
	UpdateSysApplicationResp = pb.UpdateSysApplicationResp
	User                     = pb.User
	UserMenusResp            = pb.UserMenusResp
	UserPermsVerifyReq       = pb.UserPermsVerifyReq
	UserReq                  = pb.UserReq

	Application interface {
		CreateSysApplication(ctx context.Context, in *CreateSysApplicationReq, opts ...grpc.CallOption) (*CreateSysApplicationResp, error)
		UpdateSysApplication(ctx context.Context, in *UpdateSysApplicationReq, opts ...grpc.CallOption) (*UpdateSysApplicationResp, error)
		DeleteSysApplication(ctx context.Context, in *DeleteSysApplicationReq, opts ...grpc.CallOption) (*DeleteSysApplicationResp, error)
		DetailSysApplication(ctx context.Context, in *DetailSysApplicationReq, opts ...grpc.CallOption) (*DetailSysApplicationResp, error)
		PageSysApplication(ctx context.Context, in *SearchSysApplicationReq, opts ...grpc.CallOption) (*SearchSysApplicationResp, error)
	}

	defaultApplication struct {
		cli zrpc.Client
	}
)

func NewApplication(cli zrpc.Client) Application {
	return &defaultApplication{
		cli: cli,
	}
}

func (m *defaultApplication) CreateSysApplication(ctx context.Context, in *CreateSysApplicationReq, opts ...grpc.CallOption) (*CreateSysApplicationResp, error) {
	client := pb.NewApplicationClient(m.cli.Conn())
	return client.CreateSysApplication(ctx, in, opts...)
}

func (m *defaultApplication) UpdateSysApplication(ctx context.Context, in *UpdateSysApplicationReq, opts ...grpc.CallOption) (*UpdateSysApplicationResp, error) {
	client := pb.NewApplicationClient(m.cli.Conn())
	return client.UpdateSysApplication(ctx, in, opts...)
}

func (m *defaultApplication) DeleteSysApplication(ctx context.Context, in *DeleteSysApplicationReq, opts ...grpc.CallOption) (*DeleteSysApplicationResp, error) {
	client := pb.NewApplicationClient(m.cli.Conn())
	return client.DeleteSysApplication(ctx, in, opts...)
}

func (m *defaultApplication) DetailSysApplication(ctx context.Context, in *DetailSysApplicationReq, opts ...grpc.CallOption) (*DetailSysApplicationResp, error) {
	client := pb.NewApplicationClient(m.cli.Conn())
	return client.DetailSysApplication(ctx, in, opts...)
}

func (m *defaultApplication) PageSysApplication(ctx context.Context, in *SearchSysApplicationReq, opts ...grpc.CallOption) (*SearchSysApplicationResp, error) {
	client := pb.NewApplicationClient(m.cli.Conn())
	return client.PageSysApplication(ctx, in, opts...)
}
